param(
    [string]$OutputDir = "dist",
    [string]$Version
)

$ErrorActionPreference = "Stop"
$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")

function Resolve-OutputDir {
    param([string]$Path)

    if ([System.IO.Path]::IsPathRooted($Path)) {
        return (Resolve-Path $Path).Path
    }
    return (Resolve-Path (Join-Path $RepoRoot $Path)).Path
}

function Format-Bytes {
    param([long]$Bytes)

    if ($Bytes -ge 1GB) {
        return "{0:N2} GB" -f ($Bytes / 1GB)
    }
    if ($Bytes -ge 1MB) {
        return "{0:N2} MB" -f ($Bytes / 1MB)
    }
    if ($Bytes -ge 1KB) {
        return "{0:N1} KB" -f ($Bytes / 1KB)
    }
    return "$Bytes B"
}

function Get-ArtifactPurpose {
    param([string]$Name)

    if ($Name -match "Setup-.*\.exe$") {
        return "Guided installer for normal Windows users"
    }
    if ($Name -match "windows-source-test\.zip$") {
        return "Source test package for developers and early testers"
    }
    return "Release asset"
}

function Get-HashMap {
    param([string]$HashPath)

    $map = @{}
    if (-not (Test-Path $HashPath)) {
        return $map
    }

    foreach ($line in Get-Content -LiteralPath $HashPath -Encoding ASCII) {
        if ($line -match "^\s*([0-9A-Fa-f]{64})\s+\*?(.+?)\s*$") {
            $map[$Matches[2]] = $Matches[1].ToUpperInvariant()
        }
    }
    return $map
}

$distRoot = Resolve-OutputDir $OutputDir
$hashPath = Join-Path $distRoot "SHA256SUMS.txt"
$manifestPath = Join-Path $distRoot "RELEASE-ASSETS.md"
$hashMap = Get-HashMap -HashPath $hashPath
$artifacts = @(
    Get-ChildItem -LiteralPath $distRoot -File |
        Where-Object { $_.Extension -in @(".exe", ".zip") } |
        Sort-Object Name
)

if (-not $artifacts.Count) {
    throw "No .exe or .zip release artifacts found under $distRoot"
}

$displayVersion = if ($Version) { $Version } else { "current build" }
$lines = @(
    "# Release Assets",
    "",
    "Version: $displayVersion",
    "",
    "This file is generated by scripts/write-release-assets.ps1 so release uploaders and early testers can choose the right file without guessing.",
    "",
    "## What To Download",
    "",
    "- Normal Windows users: download the Setup .exe and SHA256SUMS.txt, verify the hash, then run the installer.",
    "- Developers / early testers: download the windows-source-test.zip and SHA256SUMS.txt, then follow README-FIRST-RUN.txt inside the package.",
    "- The installer is unsigned in this preview. Continue only when the file came from the project release and the SHA256 hash matches.",
    "",
    "## Assets",
    "",
    "| File | Purpose | Size | SHA256 |",
    "| --- | --- | ---: | --- |"
)

foreach ($artifact in $artifacts) {
    $hash = if ($hashMap.ContainsKey($artifact.Name)) { $hashMap[$artifact.Name] } else { "(missing from SHA256SUMS.txt)" }
    $lines += "| $($artifact.Name) | $(Get-ArtifactPurpose $artifact.Name) | $(Format-Bytes $artifact.Length) | $hash |"
}

$lines += @(
    "",
    "## Verify On Windows",
    ""
)

foreach ($artifact in $artifacts) {
    $lines += "    Get-FileHash .\$($artifact.Name) -Algorithm SHA256"
}

$lines += @(
    "",
    "Then compare the hash output with SHA256SUMS.txt before running the installer or extracting the source package."
)

$lines | Set-Content -LiteralPath $manifestPath -Encoding UTF8
Write-Host "[OK] Wrote $manifestPath" -ForegroundColor Green
